### PR TITLE
Restyle

### PR DESCRIPTION
**Pull request by hypeJunction**
Remake of #19

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
I already cherry-picked some of the stuff from your previous PR before you made this one, so now there are conflicts.

Luckily the rest of the stuff should be easier to cherry-pick because they're now in smaller parts.

**Comment by hypeJunction** [comment]
Hm, maybe you can revert the commits?

**Comment by juho-jaakkola** [comment]
Many (but unfortunately not all) of the features have now been either cherry-picked or added manually, so I'm closing the PR.

**Comment by hypeJunction** [comment]
I still think this would make the UX a lot better: https://github.com/hypeJunction/elgg-notifier/commit/226de9dc68af74c9fd5aa6f2e0bdd5e3a32f6bc1

**Comment by juho-jaakkola** [comment]
I wouldn't want to have that by default because I have the push server implementation. Perhaps a separate plugin?

**Pull request closed without merging**
